### ISSUE TITLE
Raspberry Pi Zero 2 W support

### ISSUE THREAD

**Issue by eliasnaur** [usbarmory/tamago#35]
Zero 1 is exceedingly hard to buy these days, so I wonder how much work it would take to get Zero 2 to work with Tamago. For example, would it be reasonable for an outside contributor to do?

**Comment by abarisani** [comment]
We would be happy to accept external contributions for its architecture, I don't have personal experiene with its SoC so I cannot comment on the time/effort required. Thanks!
