### ISSUE TITLE
Device invariably "dies" after some time

### ISSUE THREAD

**Issue by marctrem** [usbarmory/tamago#37]
Dear Tamago authors,

I cannot get the device to live further than a minute on tamago.
The issue has been reproduced with tamago-go#1.18.1 and tamaga-go#1.18.3 and the latest tamago.
The bootloader is loaded using SDP.
Since I lack the debugging hardware, it's rather hard to figure the root cause. No panic is emitted.
The issue is observed with and without the sd card being inserted.

### Code
```go
func init() {
	model := imx6.Model()
	if !imx6.Native {
		banner += fmt.Sprintf(" - %s %d MHz (emulated)", model, imx6.ARMFreq()/1000000)
		return
	}
	if err := imx6.SetARMFreq(900); err != nil {
		log.Printf("WARNING: error setting ARM frequency: %v", err)
	}
}

func main() {
	select {}
}

```

### Steps
1. Plug the device
2. Flash through SDP
3. Blue led goes from soft to hard
4. Wait ~34s
5. Blue led goes from hard to soft -- device is unresponsive

## Video
https://drive.google.com/file/d/1_ianaqZ977cbfOYE3gYm8hQSo8weLGW5/view

Please let me know if I can help with that investigation.

Thank you!

**Comment by abarisani** [comment]
May I see your imports?
