### ISSUE TITLE
USB Host mode support

### ISSUE THREAD

**Issue by fabled** [usbarmory/tamago#43]
I was just able to complete a custom USB device mode support on Armory MK2.

Now I am looking to attach other peripherals to the USB-C receptacle and to communicate to those devices. Also interested in having USB passthrough (that is proxy the traffic between the computer on the USB-C plug and the peripheral connected to USB-C receptacle).

I did not see yet any host controller support code, or did I just not find it? Is support for this planned?

**Comment by abarisani** [comment]
There are no plans for host mode at this time.

**Comment by mstaack** [comment]
@abarisani any hints how to get closer to a host mode driver?

even basic midi/serial/storage hosting would be really interesting.

**Comment by abarisani** [comment]
> There are no plans for host mode at this time.

This is unchanged.
